### ISSUE TITLE
Modifier order

### ISSUE THREAD

**Issue by swift502** [ucupumar/ucupaint#1]
Hi,

This isn't a big deal but I'm wondering if it might cause confusion. 

Blender's modifiers are processed _**top to bottom**_.
Ucupaint modifiers are processed _**bottom to top**_, the other way around.

Was there a reason behind this? Wouldn't it be more intuitive to copy Blender's convention?
I admit I haven't used ucupaint long enough to see if it's confusing, but just from reading the docs it struck me as odd.

**Comment by ucupumar** [comment]
Yes, there is a reason. Because the bottom part is usually for the source settings. For example, this part has input and override settings, so modifiers will work on top of those. And the last process will be the blend operation and the intensity. So if you can see, the process is from bottom to top. I hope that's understandable.
![image](https://user-images.githubusercontent.com/5253453/178103158-8d9ff076-2795-4ace-8452-7639d7a2b318.png)

**Comment by swift502** [comment]
Yeah it makes sense. :)

I'll have to use the addon to understand everything more. But I was just wondering if there's a good reason for this, and it seems like there is.

Thanks for clarifying.

**Comment by ucupumar** [comment]
You're welcome! :)
