### ISSUE TITLE
Voronoi Distance to Edge not working

### ISSUE THREAD

**Issue by trashmaster9000** [ucupumar/ucupaint#103]
if i use the Voronoi texture and set the type to "Distance to Edge" nothing is displayed. other types seem to work.

![Bildschirmfoto_2024-04-20_13-00-25](https://github.com/ucupumar/ucupaint/assets/14186848/9bd6487b-28e9-4626-b730-ae8f4d02d9cb)
![Bildschirmfoto_2024-04-20_13-00-46](https://github.com/ucupumar/ucupaint/assets/14186848/ecb96b04-8d39-43f7-b885-187fcd95f0f8)

this is what its supposed to look like:
![Bildschirmfoto_2024-04-20_13-01-48](https://github.com/ucupumar/ucupaint/assets/14186848/8e04303a-7137-41ca-94ba-cb170b4cc9cb)

**Comment by ucupumar** [comment]
Hmm, it looks like voronoi only has one output when you use that type. This can be tricky to fix, but you can manually choose voronoi distance on layer channel input for now.
![image](https://github.com/ucupumar/ucupaint/assets/5253453/5b7ad770-25d0-4cd8-bc99-800fe0a2adc5)

**Comment by trashmaster9000** [comment]
thanks for your quick reply!

i've just encountered the next issue:
if i also activate influence to Normal Channel i get some really weird effects:
only colour:
![Bildschirmfoto_2024-04-21_11-34-09](https://github.com/ucupumar/ucupaint/assets/14186848/4b6068b4-abdb-49e1-b40c-60c65e7b1228)

with normal:
![Bildschirmfoto_2024-04-21_11-34-29](https://github.com/ucupumar/ucupaint/assets/14186848/6a42d6bc-2eca-485d-b3ea-bffcc7a602a7)


what i'm trying to achieve:
![Bildschirmfoto_2024-04-21_11-36-43](https://github.com/ucupumar/ucupaint/assets/14186848/56c878cb-53fe-4213-a339-ecff631953d4)

**Comment by ucupumar** [comment]
This is because ucupaint is using smooth bump map by default, you can change it back to the standard bump map using this setting. 
![image](https://github.com/ucupumar/ucupaint/assets/5253453/43542942-734e-4e41-969d-edd0a0670b78)
Be aware that if you're disabling the smooth bump, painted bump will look blocky
![image](https://github.com/ucupumar/ucupaint/assets/5253453/6e91a120-9117-4974-aa5a-5370eec9625b)

If you want to keep using smooth bump and want to fix voronoi bump map, you can use layer channel settings to tweak the smooth bump effects
![image](https://github.com/ucupumar/ucupaint/assets/5253453/1dcdc293-f12a-4393-b4bf-efa203dda16a)
I hope that's understandable

**Comment by trashmaster9000** [comment]
thanks for your quick support, works just fine now!
